create table if not exists public.objekty_stavby (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null references public.zoznam_zakaziek(id) on delete cascade,
  nazov text not null check (btrim(nazov) <> ''),
  poradie integer not null default 0,
  aktivny boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (zakazka_id, nazov)
);

alter table public.objekty_stavby enable row level security;
revoke all on table public.objekty_stavby from anon, authenticated;
grant select, insert, update, delete on table public.objekty_stavby to service_role;
grant usage, select on sequence public.objekty_stavby_id_seq to service_role;

alter table public.naklady_stavby
  add column if not exists objekt_id bigint references public.objekty_stavby(id) on delete set null;
alter table public.faktury_dodavatelov
  add column if not exists objekt_id bigint references public.objekty_stavby(id) on delete set null;
alter table public.dochadzka
  add column if not exists objekt_id bigint references public.objekty_stavby(id) on delete set null;
alter table public.uhrady_pracovnikov
  add column if not exists objekt_id bigint references public.objekty_stavby(id) on delete set null;
alter table public.faktury_klientov
  add column if not exists objekt_id bigint references public.objekty_stavby(id) on delete set null;
alter table public.platby_stavby
  add column if not exists objekt_id bigint references public.objekty_stavby(id) on delete set null;

create index if not exists objekty_stavby_zakazka_idx on public.objekty_stavby(zakazka_id, poradie, id);
create index if not exists naklady_stavby_objekt_idx on public.naklady_stavby(objekt_id);
create index if not exists faktury_dodavatelov_objekt_idx on public.faktury_dodavatelov(objekt_id);
create index if not exists dochadzka_objekt_idx on public.dochadzka(objekt_id);
create index if not exists uhrady_pracovnikov_objekt_idx on public.uhrady_pracovnikov(objekt_id);
create index if not exists faktury_klientov_objekt_idx on public.faktury_klientov(objekt_id);
create index if not exists platby_stavby_objekt_idx on public.platby_stavby(objekt_id);

insert into public.objekty_stavby(zakazka_id, nazov, poradie)
select z.id, x.nazov, x.poradie
from public.zoznam_zakaziek z
cross join (values
  ('Dvojdom A', 1),
  ('Dvojdom B', 2),
  ('Dvojdom C', 3)
) as x(nazov, poradie)
where trim(z.nazov) = 'Zohor Domy'
on conflict (zakazka_id, nazov) do nothing;

create or replace function public.record_attendance_secure(entries jsonb)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  item jsonb;
  r record;
begin
  if jsonb_typeof(entries) is distinct from 'array' then
    raise exception 'Expected entries array' using errcode = '22023';
  end if;
  if jsonb_array_length(entries) not between 1 and 200 then
    raise exception 'Invalid batch size' using errcode = '22023';
  end if;

  for item in select value from jsonb_array_elements(entries) loop
    if jsonb_typeof(item) is distinct from 'object' then
      raise exception 'Invalid entry' using errcode = '22023';
    end if;

    if not (item ? 'meno' and item ? 'zakazka' and item ? 'datum' and item ? 'prichod' and item ? 'odchod')
      or exists (
        select 1 from jsonb_object_keys(item) k
        where k not in ('meno','zakazka','datum','prichod','odchod','objekt_id')
      )
      or jsonb_typeof(item->'meno') <> 'string'
      or jsonb_typeof(item->'zakazka') <> 'string'
      or jsonb_typeof(item->'datum') <> 'string'
      or jsonb_typeof(item->'prichod') <> 'string'
      or jsonb_typeof(item->'odchod') <> 'string'
      or btrim(coalesce(item->>'meno','')) = ''
      or length(item->>'meno') > 200
      or btrim(coalesce(item->>'zakazka','')) = ''
      or length(item->>'zakazka') > 300
      or coalesce(item->>'datum','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      or coalesce(item->>'prichod','') !~ '^([01][0-9]|2[0-3]):(00|15|30|45)$'
      or coalesce(item->>'odchod','') !~ '^([01][0-9]|2[0-3]):(00|15|30|45)$'
      or item->>'prichod' = item->>'odchod'
      or (
        item ? 'objekt_id'
        and item->'objekt_id' <> 'null'::jsonb
        and (
          jsonb_typeof(item->'objekt_id') <> 'number'
          or (item->>'objekt_id')::numeric <= 0
          or (item->>'objekt_id')::numeric <> trunc((item->>'objekt_id')::numeric)
        )
      ) then
      raise exception 'Invalid values' using errcode = '22023';
    end if;
  end loop;

  if (select count(distinct value->>'meno') from jsonb_array_elements(entries)) <> jsonb_array_length(entries)
    or (select count(distinct (value->>'datum', value->>'zakazka', value->>'prichod', value->>'odchod', coalesce(value->>'objekt_id','')))
        from jsonb_array_elements(entries)) <> 1 then
    raise exception 'Invalid batch' using errcode = '22023';
  end if;

  lock table public.dochadzka in share row exclusive mode;

  for r in
    select *
    from jsonb_to_recordset(entries)
      as e(meno text, zakazka text, datum date, prichod time, odchod time, objekt_id bigint)
  loop
    if not exists(
      select 1 from public.zamestnanci z
      where z.meno = r.meno and coalesce(z.aktivny, true) = true
    )
    or not exists(
      select 1 from public.zoznam_zakaziek z
      where z.nazov = r.zakazka and z.stav = 'Aktívna'
    ) then
      raise exception 'Unknown worker or inactive job' using errcode = '22023';
    end if;

    if r.objekt_id is not null and not exists(
      select 1
      from public.objekty_stavby o
      join public.zoznam_zakaziek z on z.id = o.zakazka_id
      where o.id = r.objekt_id
        and o.aktivny = true
        and z.nazov = r.zakazka
    ) then
      raise exception 'Invalid project object' using errcode = '22023';
    end if;

    if exists(
      select 1 from public.dochadzka d
      where d.meno = r.meno
        and d.datum + d.prichod
            < r.datum + r.odchod + case when r.odchod < r.prichod then interval '1 day' else interval '0' end
        and r.datum + r.prichod
            < d.datum + d.odchod + case when d.odchod <= d.prichod then interval '1 day' else interval '0' end
    ) then
      raise exception 'Overlapping attendance' using errcode = '23505';
    end if;
  end loop;

  insert into public.dochadzka(meno, zakazka, datum, prichod, odchod, objekt_id)
  select meno, zakazka, datum, prichod, odchod, objekt_id
  from jsonb_to_recordset(entries)
    as e(meno text, zakazka text, datum date, prichod time, odchod time, objekt_id bigint);
end;
$$;

revoke all on function public.record_attendance_secure(jsonb) from public, anon, authenticated;
grant execute on function public.record_attendance_secure(jsonb) to service_role;
