create table if not exists public.platby_stavby (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null references public.zoznam_zakaziek(id) on delete cascade,
  datum date not null,
  suma numeric(14,2) not null check (suma > 0),
  popis text not null default 'Platba od klienta' check (length(trim(popis)) > 0),
  poznamka text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists platby_stavby_zakazka_datum_idx
  on public.platby_stavby(zakazka_id, datum desc);

alter table public.platby_stavby enable row level security;

revoke all on table public.platby_stavby from anon, authenticated;
revoke all on sequence public.platby_stavby_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.platby_stavby to service_role;
grant usage, select on sequence public.platby_stavby_id_seq to service_role;
