create table if not exists public.uhrady_pracovnikov (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null references public.zoznam_zakaziek(id) on delete cascade,
  meno text not null check (length(trim(meno)) > 0),
  datum date not null,
  suma numeric(14,2) not null check (suma > 0),
  poznamka text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists uhrady_pracovnikov_zakazka_datum_idx
  on public.uhrady_pracovnikov(zakazka_id, datum desc);

create index if not exists uhrady_pracovnikov_meno_datum_idx
  on public.uhrady_pracovnikov(meno, datum desc);

alter table public.uhrady_pracovnikov enable row level security;

revoke all on table public.uhrady_pracovnikov from anon, authenticated;
revoke all on sequence public.uhrady_pracovnikov_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.uhrady_pracovnikov to service_role;
grant usage, select on sequence public.uhrady_pracovnikov_id_seq to service_role;
