create table if not exists public.financie_stavby (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null unique references public.zoznam_zakaziek(id) on delete cascade,
  cena_zakazky numeric(14,2) not null default 0 check (cena_zakazky >= 0),
  budget_nakladov numeric(14,2) not null default 0 check (budget_nakladov >= 0),
  vyfakturovane numeric(14,2) not null default 0 check (vyfakturovane >= 0),
  prijate_platby numeric(14,2) not null default 0 check (prijate_platby >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.naklady_stavby (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null references public.zoznam_zakaziek(id) on delete cascade,
  datum date not null,
  popis text not null check (length(trim(popis)) > 0),
  kategoria text not null check (kategoria in ('Pracovníci','Materiál','Subdodávatelia','Mechanizácia','Ostatné')),
  suma numeric(14,2) not null check (suma > 0),
  poznamka text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists naklady_stavby_zakazka_id_idx
  on public.naklady_stavby(zakazka_id);

create index if not exists naklady_stavby_zakazka_datum_idx
  on public.naklady_stavby(zakazka_id, datum desc);

alter table public.financie_stavby enable row level security;
alter table public.naklady_stavby enable row level security;

revoke all on table public.financie_stavby from anon, authenticated;
revoke all on table public.naklady_stavby from anon, authenticated;
revoke all on sequence public.financie_stavby_id_seq from anon, authenticated;
revoke all on sequence public.naklady_stavby_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.financie_stavby to service_role;
grant select, insert, update, delete on table public.naklady_stavby to service_role;
grant usage, select on sequence public.financie_stavby_id_seq to service_role;
grant usage, select on sequence public.naklady_stavby_id_seq to service_role;
