create table if not exists public.faktury_klientov (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null references public.zoznam_zakaziek(id) on delete cascade,
  cislo_faktury text not null unique check (length(trim(cislo_faktury)) > 0),
  datum_vystavenia date not null,
  datum_splatnosti date not null,
  suma numeric(14,2) not null check (suma > 0),
  uhradene boolean not null default false,
  datum_uhrady date,
  poznamka text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (datum_splatnosti >= datum_vystavenia),
  check (
    (uhradene = false and datum_uhrady is null)
    or
    (uhradene = true and datum_uhrady is not null)
  )
);

create index if not exists faktury_klientov_zakazka_splatnost_idx
  on public.faktury_klientov(zakazka_id, datum_splatnosti);

create index if not exists faktury_klientov_uhradene_splatnost_idx
  on public.faktury_klientov(uhradene, datum_splatnosti);

alter table public.faktury_klientov enable row level security;

revoke all on table public.faktury_klientov from anon, authenticated;
revoke all on sequence public.faktury_klientov_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.faktury_klientov to service_role;
grant usage, select on sequence public.faktury_klientov_id_seq to service_role;
