create table if not exists public.faktury_dodavatelov (
  id bigint generated by default as identity primary key,
  zakazka_id bigint not null references public.zoznam_zakaziek(id) on delete cascade,
  dodavatel text not null check (length(trim(dodavatel)) > 0),
  cislo_faktury text not null check (length(trim(cislo_faktury)) > 0),
  datum_vystavenia date not null,
  datum_splatnosti date not null,
  kategoria text not null check (
    kategoria = any (array[
      'Pracovníci'::text,
      'Materiál'::text,
      'Subdodávatelia'::text,
      'Mechanizácia'::text,
      'Ostatné'::text
    ])
  ),
  suma numeric(14,2) not null check (suma > 0),
  uhradene boolean not null default false,
  datum_uhrady date,
  poznamka text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (datum_splatnosti >= datum_vystavenia),
  check ((uhradene = false and datum_uhrady is null) or uhradene = true)
);

create index if not exists faktury_dodavatelov_zakazka_splatnost_idx
  on public.faktury_dodavatelov(zakazka_id, datum_splatnosti);

create index if not exists faktury_dodavatelov_uhradene_splatnost_idx
  on public.faktury_dodavatelov(uhradene, datum_splatnosti);

alter table public.faktury_dodavatelov enable row level security;

revoke all on table public.faktury_dodavatelov from anon, authenticated;
revoke all on sequence public.faktury_dodavatelov_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.faktury_dodavatelov to service_role;
grant usage, select on sequence public.faktury_dodavatelov_id_seq to service_role;
