create table if not exists public.nepritomnosti (
  id bigint generated by default as identity primary key,
  datum date not null,
  meno text not null,
  dovod text not null check (length(trim(dovod)) > 0),
  created_at timestamptz not null default now(),
  constraint nepritomnosti_datum_meno_unique unique (datum, meno)
);

alter table public.nepritomnosti enable row level security;

drop policy if exists "nepritomnosti_select_anon" on public.nepritomnosti;
create policy "nepritomnosti_select_anon"
on public.nepritomnosti
for select
to anon
using (true);

drop policy if exists "nepritomnosti_insert_anon" on public.nepritomnosti;
create policy "nepritomnosti_insert_anon"
on public.nepritomnosti
for insert
to anon
with check (true);

drop policy if exists "nepritomnosti_delete_anon" on public.nepritomnosti;
create policy "nepritomnosti_delete_anon"
on public.nepritomnosti
for delete
to anon
using (true);
